format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$sudo\
$cmd_duration\
$time\
$status\
$shell\
$character\
"""

add_newline = false
command_timeout = 100

[hostname]
style = "bold italic purple"
format = "☁️  "

[time]
disabled = false # enabled!
[shell]
disabled = false # enabled!
style = "none"
