name: Build and Cache

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - uses: cachix/cachix-action@v15
        with:
          name: jeremyschlatter-env
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix build
